services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sprphone
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sprphone
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - sprphone

volumes:
  pgdata:

networks:
  sprphone:
    external: true
