services:
  sprphone:
    container_name: sprphone
    image: hellcorp.local/sprphone:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
    networks:
      - sprphone

networks:
  sprphone:
    external: true
