services:
  sprphone:
    container_name: sprphone
    image: sprphone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - sprphone
networks:
  sprphone:
    external: true